<!-- BEGIN common/search-form.phtml -->

<?php
$translate = $this->plugin('translate');
$searchValue = $this->escapeHtml($this->params()->fromQuery('search', ''));
?>

<form action="<?= $this->escapeHtml($this->url('site/resource', ['controller' => 'item','action' => 'browse'], true)) ?>"
            id="search-form"
            class="rdt-search-form">
    <input type="text" name="search"
           value="<?php echo $searchValue; ?>"
           placeholder="<?php echo $translate('Search'); ?>">
</form>

<!-- END common/search-form.phtml -->
