<!-- BEGIN browse.phtml -->

<?php
  $query = $this->params()->fromQuery();
  $sortHeadings = [
    [
        'label' => 'Title',
        'value' => 'dcterms:title'
    ],
    [
        'label' => 'Identifier',
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => 'Class',
        'value' => 'resource_class_label'
    ],
    [
        'label' => 'Created',
        'value' => 'created'
    ],
];
?>

<div class="browse-controls">
  <?= $this->pagination(); ?>

  <?= $this->sortSelector($sortHeadings); ?>

  <div class="rdt-advanced-search-link">
             (Or, use
  <?= 
    $this->hyperlink(
        'advanced search', 
        $this->url(
            'site/resource', 
            ['controller' => 'item', 'action' => 'search'],
            ['query' => $query],
             true
        ), ['class' => 'advanced-search']
    )
                ?>.)
  </div>

</div>

<div class="rdt-browse-results">
<?php
foreach (array_chunk($items, 2) as $row_group) {
?>

<div class="rdt-browse-row">

<?php
    $item1 = $row_group[0];
    if (isset($row_group[1])) {
        $item2 = $row_group[1];
    }
?>

  <div class="rdt-browse-item">
    <span><?= $item1->linkRaw($item1->value('dcterms:title')) ?></span>
    <div class="rdt-browse-thumbnail-cell">
      <?= $item1->linkRaw($this->thumbnail($item1, 'medium')) ?>
    </div>
  </div>

<?php 
if ($item2) {
?>
  <div class="rdt-browse-item">
    <span><?= $item2->linkRaw($item2->value('dcterms:title')) ?></span>
    <div class="rdt-browse-thumbnail-cell">
      <?= $item2->linkRaw($this->thumbnail($item2, 'medium')) ?>
    </div>
  </div>
<?php
}
?>

</div>

<?php
}
?>
</table>

<!-- END browse.phtml -->
