<!-- BEGIN browse.phtml -->

<?php
  $query = $this->params()->fromQuery();
  $sortHeadings = [
    [
        'label' => 'Title',
        'value' => 'dcterms:title'
    ],
    [
        'label' => 'Identifier',
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => 'Class',
        'value' => 'resource_class_label'
    ],
    [
        'label' => 'Created',
        'value' => 'created'
    ],
];
?>

<div class="browse-controls">

  <?= $this->sortSelector($sortHeadings); ?>

  <div class="rdt-advanced-search-link">
             (Or, use
  <?= 
    $this->hyperlink(
        'advanced search', 
        $this->url(
            'site/resource', 
            ['controller' => 'item', 'action' => 'search'],
            ['query' => $query],
             true
        ), ['class' => 'advanced-search']
    )
                ?>.)
  </div>

</div>

<div class="">
<?php
foreach (array_chunk($items, 4) as $row_group) {
?>

<div class="row">

<?php
    $item1 = $row_group[0];
    if (isset($row_group[1])) {
        $item2 = $row_group[1];
    }
    if (isset($row_group[2])) {
        $item3 = $row_group[2];
    }
    if (isset($row_group[3])) {
        $item4 = $row_group[3];
    }
?>


  <div class="col-3">
    <div class="fays-item">
        <?= $item1->linkRaw($this->thumbnail($item1, 'medium')) ?>
    </div>
    <div class="fays-item-caption h4"><?= $item1->linkRaw($item1->value('dcterms:title')) ?></div>
  </div>

    <?php
    //col2
    if (isset($item2)) {
    ?>
        <div class="col-3">
            <div class="fays-item">
                <?= $item2->linkRaw($this->thumbnail($item2, 'medium')) ?>
            </div>
            <div class="fays-item-caption h4"><?= $item2->linkRaw($item2->value('dcterms:title')) ?></div>
        </div>
    <?php
    }
    ?>

    <?php
    //col3
    if (isset($item3)) {
        ?>
        <div class="col-3">
            <div class="fays-item">
                <?= $item3->linkRaw($this->thumbnail($item3, 'medium')) ?>
            </div>
            <div class="fays-item-caption h4"><?= $item3->linkRaw($item3->value('dcterms:title')) ?></div>
        </div>
        <?php
    }
    ?>


    <?php
    //col4
    if (isset($item4)) {
        ?>
        <div class="col-3">
            <div class="fays-item">
                <?= $item4->linkRaw($this->thumbnail($item4, 'medium')) ?>
            </div>
            <div class="fays-item-caption h4"><?= $item4->linkRaw($item4->value('dcterms:title')) ?></div>
        </div>
        <?php
    }
    ?>



</div>


<?php
}
?>
</div>

<?= $this->pagination(); ?>
<!-- END browse.phtml -->
