<?php
  $query = $this->params()->fromQuery();
  $sortHeadings = [
    [
        'label' => 'Title',
        'value' => 'dcterms:title'
    ],
    [
        'label' => 'Identifier',
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => 'Class',
        'value' => 'resource_class_label'
    ],
    [
        'label' => 'Created',
        'value' => 'created'
    ],
];
?>

<h3>Items</h3>

<div class="browse-controls">
  <?= $this->pagination(); ?>
  <?= 
    $this->hyperlink(
        'Advanced search', 
        $this->url(
            'site/resource', 
            ['controller' => 'item', 'action' => 'search'],
            ['query' => $query],
             true
        ), ['class' => 'advanced-search']
    )
  ?>
  <?= $this->sortSelector($sortHeadings); ?>
</div>


<?php
foreach ($items as $item):
    $title = $item->value('dcterms:title');
    $body = $item->value('dcterms:description');
?>

  <?= $item->linkRaw($this->thumbnail($item, 'medium')) ?>
  <?= $title ?>

<?php
endforeach;
?>
