<div class="row">
<?php foreach ($this->resources as $resource): ?>
    <div class="<?php echo $this->resourceType; ?> col-6">
        <div class="fays-item">

            <?php echo $resource->linkRaw($this->thumbnail($resource, 'medium', ['title' => $heading])); ?>
             <div class="fays-item-caption"><?= $resource->link($resource->displayTitle()); ?></div>
        </div>
    </div>
<?php endforeach; ?>
<!-- Masonry grid items use floats so they need to be cleared -->
<div class="rdt-clearleft"></div>
</div>
