<?php

// As the stylesheet stack is empty by default, the use of append vs. prepend is
// irrelevant in this context.
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headLink(['rel' => 'icon', 'href' => $this->assetUrl('img/favicon.png')]);

// Masonry 4.2.2.
$this->headScript()->appendFile($this->assetUrl('js/vendor/masonry.js'));
$this->headScript()->appendFile($this->assetUrl('js/reanimated.js'));
?>

<?= $this->doctype() ?>

<html>
  <head>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
  </head>

  <body>

  <?= $site->publicNav()->menu() ?>
  <?= $this->content ?>

  </body>
</html>
