<?php

// As the stylesheet stack is empty by default, the use of append vs. prepend is
// irrelevant in this context.
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headLink(['rel' => 'icon', 'href' => $this->assetUrl('img/favicon.png')]);

// Masonry 4.2.2.
$this->headScript()->appendFile($this->assetUrl('js/vendor/masonry.js'));
$this->headScript()->appendFile($this->assetUrl('js/reanimated.js'));
?>

<?= $this->doctype() ?>

<html>
  <head>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
  </head>

  <body>
    <header>
       <h1><?= $site->title() ?></h1>

       <img src="<?= $this->assetUrl('img/pulse_logo.png') ?>" class="rdt-logo"/>

    </header>

    <div class="rdt-container">
       <div class="rdt-side-menu">
         <?= $site->publicNav()->menu() ?>
       </div>
       <div class="rdt-main-content">
         <?= $this->content ?>
       </div>
    </div>


    <footer>
<?php if ($footerContent = $this->themeSetting('footer')): ?>
<?php echo $footerContent; ?>
<?php else: ?>
<?php echo $this->translate('Powered by Omeka S'); ?>
<?php endif; ?>
    </footer>
  </body>
</html>
